[[language]]
name = "python"
roots = ["pyproject.toml"]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
formatter = { command = "black", args = ["-", "-q"] }
auto-format = true
config = {}

[[language]]
name = "djangohtml"
scope = "source.html.django"
file-types = []
roots = []
auto-format = true
formatter = { command = "djlint", args = ["-", "--reformat", "--quiet"] }

