# theme = "catppuccin_mocha"
# theme = "monokai_pro"
theme = "sonokai"

[editor]
line-number = "relative"
bufferline = "always"
cursorline = true
color-modes = true
true-color = true
scrolloff = 10

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "file-modification-indicator"]
right = ["diagnostics", "position-percentage", "position", "separator", "file-encoding", "file-line-ending", "file-type"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[keys.normal]
C-d = ["half_page_down", "goto_window_center"]
C-u = ["half_page_up", "goto_window_center"]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
X = ["extend_line_up", "extend_to_line_bounds"]
"tab" = "goto_next_buffer"
"S-tab" = "goto_previous_buffer"
C-x = ":bc"
C-X = ":bc!"
A-z = ":toggle-option soft-wrap.enable"
A-l = ":toggle lsp.display-inlay-hints"
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.select]
C-d = ["half_page_down", "goto_window_center"]
C-u = ["half_page_up", "goto_window_center"]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
X = ["extend_line_up", "extend_to_line_bounds"]
