[[language]]
name = "python"
language-servers = ["pyright"]
formatter = { command = "black", args = ["-", "-q"] }
auto-format = true

[[language]]
name = "htmldjango"
scope = "source.htmldjango"
file-types = []
roots = []
auto-format = true
formatter = { command = "djlint", args = ["-", "--reformat", "--quiet"] }

[[grammar]]
name = "htmldjango"
source = { git = "https://github.com/interdependence/tree-sitter-htmldjango", rev = "b2dba02eddab66be669022320273d0dfe1ff923d" }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }

[[language]]
name = "toml"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "toml"] }

[[language]]
name = "templ"
auto-format = true

[[grammar]]
name = "templ"
source = { git = "https://github.com/vrischmann/tree-sitter-templ", rev = "c3baaab33f1f1032eedd3613cd932284975bd21f" }
