theme = "catppuccin_mocha"

[editor]
line-number = "relative"
bufferline = "multiple"
cursorline = true
color-modes = true
true-color = true
scrolloff = 10

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
right = ["diagnostics", "selections", "position-percentage", "position", "separator", "file-encoding", "file-line-ending", "file-type"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[keys.normal]
C-d = ["half_page_down", "goto_window_center"]
C-u = ["half_page_up", "goto_window_center"]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
G = "goto_file_end"
X = "extend_line_up"
ret = ["move_line_down", "goto_line_end"]
A-z = ":toggle-option soft-wrap.enable"
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
space = {w = ":w", x = ":bc", X = ":bc!", q = ":q", Q = ":q!"}

[keys.select]
C-d = ["half_page_down", "goto_window_center"]
C-u = ["half_page_up", "goto_window_center"]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
G = "goto_file_end"
