[[language]]
name = "python"
roots = ["pyproject.toml"]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
formatter = { command = "black", args = ["-", "-q"] }
auto-format = true
config = {}

[[language]]
name = "htmldjango"
scope = "source.htmldjango"
file-types = []
roots = []
auto-format = true
formatter = { command = "djlint", args = ["-", "--reformat", "--quiet"] }

[[grammar]]
name = "htmldjango"
source = { git = "https://github.com/interdependence/tree-sitter-htmldjango" , rev = "b2dba02eddab66be669022320273d0dfe1ff923d" }
