# theme = "catppuccin_mocha"
# theme = "monokai_pro"
# theme = "sonokai"
theme = "nord-night"

[editor]
line-number = "relative"
bufferline = "always"
cursorline = true
color-modes = true
true-color = true
scrolloff = 10

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]

right = [
  "diagnostics",
  "selections",
  "register",
  "position-percentage",
  "position",
  "separator",
  "file-encoding",
  "file-line-ending",
  "file-type",
]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[keys.normal]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
"0" = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
"G" = "goto_file_end"
"%" = "match_brackets"

"X" = ["extend_line_up", "extend_to_line_bounds"]
"i" = ["insert_mode", "collapse_selection"]
"a" = ["append_mode", "collapse_selection"]

"esc" = ["collapse_selection", "keep_primary_selection"]
"tab" = "goto_next_buffer"
"S-tab" = "goto_previous_buffer"
"C-q" = ":bc!"
"A-z" = ":toggle-option soft-wrap.enable"
"A-l" = ":toggle lsp.display-inlay-hints"
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.select]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
"0" = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
"G" = "goto_file_end"
"%" = "match_brackets"

"X" = ["extend_line_up", "extend_to_line_bounds"]
"i" = ["insert_mode", "collapse_selection"]
"a" = ["append_mode", "collapse_selection"]

[keys.insert]
"C-space" = "signature_help"

# [keys.insert.j]
# "k" = "normal_mode"
